# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('beverage', 'Beverage'), ('dish', 'Dish'), ('dessert', 'Desert')], default='beverage', max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('queue', 'Queue'), ('preparing', 'Preparing'), ('done', 'Done')], default='queue', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.Product'),
        ),
        migrations.AddField(
            model_name='item',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.Request'),
        ),
    ]
