# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0004_request_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting Payment'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('done', 'Done')], default='waiting', max_length=50),
        ),
    ]
