# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
