# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('role', models.CharField(choices=[('Project Manager', 'Project Manager'), ('Developer', 'Developer'), ('Designer', 'Designer')], default='Developer', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
